import { SinglePost } from "@/components/Post/SinglePost";
import { MetaData, getAllPosts } from "@/lib/notionApi";
import Head from "next/head";

// SSG(ISR)の設定
// build時にデータを全てレンダリング→その後60sに一度レンダリングし直し、最新に保つ
// (参考)https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props
export async function getStaticProps() {
  const allPosts = await getAllPosts();
  return {
    props: {
      allPosts,
    },
    revalidate: 60,
  };
}

type Props = {
  allPosts: MetaData[];
};
export default function Home({ allPosts }: Props) {
  return (
    <div className="container w-full h-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        {allPosts.map((post: MetaData, index: number) => (
          <div key={index} className="mx-4">
            <SinglePost {...post} />
          </div>
        ))}
      </main>
    </div>
  );
}
